use_frameworks!

platform :ios, '9.0'

target 'JZTUniBoost_Example' do
  pod 'JZTUniBoost', :path => '../'

  target 'JZTUniBoost_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
